### ISSUE TITLE
How to generate a similar gif?

### ISSUE THREAD

**Issue by rakuyoMo** [MasonSlover/MasonSlover#1]
I like this gif in this warehouse very much. Its effect is amazing.

I hope to make a similar gif animation, is there any tutorial?

**Comment by MasonSlover** [comment]
Hey! 

Thank you, the source code is in the repository. If you download Processing (processingfoundation.org), you can edit and run the .pde to get the effect.

**Comment by rakuyoMo** [comment]
> Hey! 
> 
> Thank you, the source code is in the repository. If you download Processing (processingfoundation.org), you can edit and run the .pde to get the effect. 
> 
> > On Oct 27, 2020, at 5:33 AM, Rakuyo <notifications@github.com> wrote:
> > 
> > ﻿
> > I like this gif in this warehouse very much. Its effect is amazing.
> > 
> > I hope to make a similar gif animation, is there any tutorial?
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

Sorry, I first contacted `.pde`. how can I execute the file?

**Comment by rakuyoMo** [comment]
> Hey! Thank you, the source code is in the repository. If you download Processing (processingfoundation.org), you can edit and run the .pde to get the effect.
> […](#)

Hello, I have downloaded **Processing** and successfully ran the `.pde` file, but I am not sure how to generate a `.gif` file. Where can I get some help?
